# Copyright (c) 2016-present Sven Greb <development@svengreb.de>
# This source code is licensed under the MIT license found in the license file.

#+----------------+
#+ Plugin Support +
#+----------------+
#+--- tmux-prefix-highlight ---+
set -g @prefix_highlight_output_prefix "#[fg=brightcyan]#[bg=black]#[nobold]#[noitalics]#[nounderscore]#[bg=brightcyan]#[fg=black]"
set -g @prefix_highlight_output_suffix ""
set -g @prefix_highlight_copy_mode_attr "fg=brightcyan,bg=black,bold"
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_prefix_prompt 'PREFIX'

#+--------+
#+ Status +
#+--------+
#+--- Bars ---+
set -g status-style "bg=default"
set -g status-left "#{?client_prefix,#[fg=black]#[bg=yellow]#[bold],#[fg=black]#[bg=blue]#[bold]} #S #{?client_prefix,#[fg=yellow]#[bg=default]#[nobold]#[noitalics]#[nounderscore],#[fg=blue]#[bg=default]#[nobold]#[noitalics]#[nounderscore]}"
set -g status-left-length 100
set -g status-right-length 100
set -g status-right '#{prefix_highlight}#[fg=#4C566A,bg=default]#[fg=white,bg=#4C566A] #(gitmux -cfg $HOME/.gitmux.conf "#{pane_current_path}")#[bg=#4C566A] #[fg=#4C566A,bg=default]#{?#{pomodoro_status}, ,}#[fg=#D8DEE9,bg=default]#{?#{pomodoro_status},,}#[fg=#2E3440,bg=#D8DEE9]#{pomodoro_status}#{?#{pomodoro_status}, ,}#[fg=#D8DEE9,bg=default]#{?#{pomodoro_status},,}'

#+--- Windows ---+
set -g window-status-format "#{?#{==:#{@claude-status},running},#[fg=#2E3440]#[bg=#A3BE8C]#[nobold]#[noitalics]#[nounderscore] #[fg=#2E3440]#[bg=#A3BE8C]#I #{?#{e|>=:#{window_width},150},| #{=15:window_name} ,}#[fg=#A3BE8C]#[bg=default]#[nobold]#[noitalics]#[nounderscore],#{?#{==:#{@claude-status},waiting},#[fg=#2E3440]#[bg=#BF616A]#[nobold]#[noitalics]#[nounderscore] #[fg=#2E3440]#[bg=#BF616A]#I #{?#{e|>=:#{window_width},150},| #{=15:window_name} ,}#[fg=#BF616A]#[bg=default]#[nobold]#[noitalics]#[nounderscore],#[fg=#2E3440]#[bg=brightblack]#[nobold]#[noitalics]#[nounderscore] #[fg=white]#[bg=brightblack]#I #{?#{e|>=:#{window_width},150},| #{=15:window_name} ,}#[fg=brightblack]#[bg=default]#[nobold]#[noitalics]#[nounderscore]}}"
set -g window-status-current-format "#[fg=#2E3440,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#I #[fg=black,bg=cyan]| #[fg=black,bg=cyan]#{?#{e|<:#{window_width},150},#{=8:window_name}…,#W} #[fg=cyan,bg=default,nobold,noitalics,nounderscore]"
set -g window-status-separator ""
